// src/context/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect } from "react";
import api from "../../services/api";

const translations = {
  en: {
    // ===== COMMON =====
    app_name: "Crew Management System",
    sign_in: "Sign In",
    sign_out: "Sign Out",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    export: "Export",
    import: "Import",
    add: "Add",
    add_crew: "Add Crew",
    add_new: "Add New",
    search: "Search",
    search_placeholder: "Search by name, code, vessel...",
    no_data: "No data found",
    loading: "Loading...",
    yes: "Yes",
    no: "No",
    ok: "OK",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    showing: "Showing",
    of: "of",
    entries: "entries",
    record_registered: "Record registered successfully.",
    register_new: "Register New",
    enter_details: "Enter the details below to add a new",
    record: "record",
    reset: "Reset",
    save_record: "Save Record",
    overview: "Overview",
    total: "Total",
    new_person: "New Person",

    // ===== NAVIGATION =====
    dashboard: "Dashboard",
    crew: "Crew",
    "crew management": "Crew Management",
    register: "Register",
    payment: "Payment",
    settings: "Settings",
    calendar: "Calendar",

    // ===== LOGIN =====
    user_name: "User Name",
    password: "Password",
    remember_me: "Remember Me",
    forgot_password: "Forgot Password?",
    login_success: "Login successful!",
    login_failed: "Login failed. Please check your credentials.",

    // ===== CREW =====
    crew_management: "Crew Management",
    total_crews: "Total Crews",
    on_board: "On Board",
    active_crews: "Active Crews",
    compliance_issues: "Compliance Issues",
    boarding_vessel: "Boarding Vessel",
    rank: "Rank",
    seaman_code: "Seaman Code",
    name: "Name",
    validity: "Validity",
    division: "Division",
    type: "Type",
    remaining: "Remaining",
    note: "Note",
    actions: "Actions",
    view_details: "View Details",

    // ===== CERTIFICATE / SUMMARY =====
    certificate: "Certificate",
    contract: "Contract",
    ppt: "PPT",
    expire: "Expire",
    days: "Days",
    see_all: "See All →",
    vessel_name: "Vessel's Name",
    crew_class: "Crew Class",
    sign_on: "Sign On",
    sign_off: "Sign Off",
    include_period_contract: "Include Period Contract",
    expired: "Expired",
    active: "Active",
    inactive: "InActive",
    expired_contracts: "Expired Contracts",
    expire_soon: "Expire Soon",
    crew_name: "Crew Name",
    overdue: "Overdue",
    education_name: "Education Name",
    expire_date: "Expire Date",
    remaining_date: "Remaining Date",

    // ===== DASHBOARD =====
    dashboard_overview: "Dashboard Overview",
    total_crew: "Total Crew",
    active_on_board: "Active on Board",
    pending_contracts: "Pending Contracts",
    expiring_certs: "Expiring Certs",
    quick_actions: "Quick Actions",
    recent_activity: "Recent Activity",
    upcoming_tasks: "Upcoming Tasks",

    // ===== FOOTER =====
    all_rights_reserved: "All rights reserved.",
    privacy_policy: "Privacy Policy",
    terms: "Terms",
    support: "Support",
    version: "Version",

    // ===== MESSAGES =====
    logout_success: "Logout successful!",
    logout_failed: "Logout failed.",
    crew_created: "Crew created successfully.",
    crew_updated: "Crew updated successfully.",
    crew_deleted: "Crew deleted successfully.",
    crew_not_found: "Crew not found.",
    confirm_delete: "Are you sure you want to delete?",
    confirm_delete_message:
      "Do you really want to delete this records? This process cannot be undone.",

    // ===== PROFILE =====
    profile: "Profile",
    personal_info: "Personal Information",
    contact_info: "Contact Information",
    details_info: "Details Information",
    address: "Address",
    phone: "Phone",
    email: "Email",
    birth_date: "Birth Date",
    nationality: "Nationality",
    religion: "Religion",

    // ===== APPOINTMENT =====
    appointment: "Appointment",
    replacement: "Replacement",
    family: "Family",
    health: "Health",
    injury: "Injury",
    experiences: "Experiences",
    evaluation: "Evaluation",
    certificates: "Certificates",
    qualification: "Qualification",
    accident: "Accident",

    // ===== PAYMENT =====
    payroll: "Payroll",
    payment_info: "Payment Information",
    bank_name: "Bank Name",
    account_number: "Account Number",
    holder_name: "Holder Name",
    relation: "Relation",
    basic_wage: "Basic Wage",
    overtime: "Overtime",
    allowances: "Allowances",
    deductions: "Deductions",
    currency: "Currency",
    payment_date: "Payment Date",

    // ===== REGISTER FORM FIELDS =====
    license_name: "License / Competency Name",
    grade_class: "Grade / Class",
    license_number: "License Number",
    issuing_authority: "Issuing Authority",
    issue_date: "Issue Date",
    expiry_date: "Expiry Date",
    status: "Status",
    crew_member: "Crew Member",
    vessel: "Vessel",
    department: "Department",
    sign_on_date: "Sign-on Date",
    expected_sign_off: "Expected Sign-off",
    port_of_engagement: "Port of Engagement",
    contract_type: "Contract Type",
    outgoing_crew: "Outgoing Crew Member",
    reliever_name: "Reliever Name",
    reliever_rank: "Reliever Rank",
    relief_port: "Relief Port",
    planned_date: "Planned Date",
    pay_period: "Pay Period",
    incident_date: "Date of Incident",
    location: "Location on Vessel",
    accident_type: "Type of Accident",
    severity: "Severity",
    reported_by: "Reported By",
    description: "Description",
    action_taken: "Action Taken",
    injury_date: "Date of Injury",
    body_part: "Body Part Affected",
    injury_type: "Injury Type",
    treatment: "Treatment Provided",
    days_off: "Days Off Work",
    fit_date: "Fit-to-work Date",
    notes: "Notes",
    next_of_kin: "Next of Kin Name",
    relationship: "Relationship",
    contact_number: "Contact Number",
    emergency_contact: "Set as Emergency Contact",
    blood_type: "Blood Type",
    last_exam: "Last Medical Exam",
    fit_expiry: "Fit-to-work Expiry",
    vaccinations: "Vaccinations",
    allergies: "Allergies",
    medical_notes: "Medical Notes",
    vessel_type: "Vessel Type",
    grt: "GRT (Gross Tonnage)",
    company: "Company",
    from_date: "From Date",
    to_date: "To Date",
    evaluation_period: "Evaluation Period",
    evaluator: "Evaluator Name",
    overall_rating: "Overall Rating (1-5)",
    technical_rating: "Technical Skills Rating (1-5)",
    teamwork_rating: "Teamwork Rating (1-5)",
    recommendation: "Recommendation",
    comments: "Comments",
    certificate_name: "Certificate Name",
    certificate_number: "Certificate Number",

    // ===== PERSONAL INFO FORM (EN) =====
    crew_code: "Crew Code",
    position: "Position",
    hire_date: "Hire Date",
    name_korean: "Name (Korean)",
    name_english: "Name (English)",
    name_chinese: "Name (Chinese)",
    address_eng: "Address (English)",
    address_korean: "Address (Korean)",
    mobile: "Mobile Number",
    emergency_1: "Emergency Contact 1",
    emergency_2: "Emergency Contact 2",
    resident_id: "Resident Registration Number",
    education_university: "Education (University)",
    education_school: "Education (School)",
    waist: "Waist",
    safety_shoes: "Safety Shoes",
    garments: "Garments",
    drinking: "Drinking (Capacity)",
    smoking: "Smoking",
    long_service: "Long Service",
    monthly_position: "Monthly Position",
    chemical: "Chemical",
    tanker: "Tanker",
    watch_office: "Watch Office",
    mariners_license: "Mariner's License",
    telecom_license: "Telecommunications License",
    physical_exam: "Physical Examination",
    seaman_handbook: "Seaman's Handbook",
    contract_period: "Employment Contract Period",
    preview: "Preview",
    choose_file: "Choose File",
    passport: "Passport",
    add_new_crew: "Add New Crew",

    // ===== PLACEHOLDERS =====
    select_option: "Please select",
    select_position: "Please select position",
    select_nationality: "Please select nationality",
    enter_license: "Enter license number",
    enter_passport: "Enter passport number",
    enter_telecom: "Enter telecom license",
    enter_physical: "Enter physical exam date",
    enter_handbook: "Enter handbook number",
    enter_contract: "Enter contract period",

    // ===== TAB PILLS =====
    tab_personal_info: "Personal Info",
    tab_qualifications: "Qualifications",
    tab_appointment: "Appointment",
    tab_replacement: "Replacement",
    tab_payment: "Payment",
    tab_family: "Family",
    tab_injury: "Injury",
    tab_health: "Health",
    tab_experiences: "Experiences",
    tab_evaluation: "Evaluation",
    tab_certificates: "Certificates",
    tab_accident: "Accident",
    crew_profile_sections: "Crew profile sections",

    // ===== QUALIFICATION FORM =====
    new_qualification: "New Qualification",
    edit_qualification: "Edit Qualification",
    expiration: "Expiration",
    training_date: "Training Date",
    attach_file: "Attach File",
    remarks: "Remarks",
    select_certificate: "Select Certificate...",
    enter_certificate_name: "Enter certificate name",
    enter_expiration: "Enter expiration",
    enter_license_number: "Enter license number",
    enter_remarks: "Enter remarks",
    upload_drag_drop: "Upload or Drag and Drop your document file",
    max_file_size: "Maximum File Size is 20MB",
    supported_file_types: "Supported File Types are .png, .jpeg, .pdf, .csv",

    // ===== APPOINTMENT FORM =====
    new_appointment: "New Appointment",
    edit_appointment: "Edit Appointment",
    deployment_division: "Deployment Division",
    deployment_content: "Deployment Content",
    ship_name: "Ship's Name",
    boarding_date: "Boarding Date",
    leaving_date: "Leaving Date",
    boarding_period: "Boarding Period",
    place: "Place",
    select_division: "Select Division...",
    select_division_first: "Please select Division first",
    select_deployment_content: "Select Deployment Content...",
    select_ship: "Select Ship...",
    select_rank: "Select Rank...",
    enter_boarding_period: "Enter boarding period",
    enter_place: "Enter place",
    select_contract: "Select Contract Type...",

    // ===== REPLACEMENT FORM =====
    new_replacement: "New Replacement",
    edit_replacement: "Edit Replacement",
    date: "Date",
    select_place: "Select Place...",

    // ===== PAYMENT FORM =====
    new_payment: "New Payment",
    edit_payment: "Edit Payment",
    account_holder: "Account Holder",
    select_bank: "Select Bank...",
    enter_account_holder: "Enter account holder name",
    enter_account_number: "Enter account number",
    select_relation: "Select Relation...",
    select_currency: "Select Currency...",

    // ===== FAMILY FORM =====
    family_details: "Family Details",
    add_family_member: "Add Family Member",
    edit_family_member: "Edit Family Member",
    no_family_members: "No family members added yet",
    fill_required_fields: "Please fill required fields",
    enter_name: "Enter name",
    update: "Update",

    // ===== EXPERIENCE FORM =====
    new_experience: "New Experience",
    edit_experience: "Edit Experience",
    company_name: "Company Name",
    area: "Area",
    ship_type: "Ship Type",
    board_leave: "Board/Leave",
    kw: "KW",
    at_least_one_experience: "You must have at least one experience record",
    enter_company_name: "Enter company name",
    enter_ship_name: "Enter ship name",
    select_area: "Select Area...",
    select_ship_type: "Select Ship Type...",
    enter_board_leave: "Enter board/leave",
    enter_grt: "Enter GRT",
    enter_kw: "Enter KW",
    select_board_leave: "Select Board/Leave...",

    // ===== ACCIDENT FORM =====
    add_accident: "Add Accident",
    edit_accident: "Edit Accident",
    accident_reason: "Accident Reason",
    re_use: "Re-use",
    accident_date: "Accident Date",
    accident_cost: "Accident Cost",
    etc: "Etc",
    choose_ship_name: "Choose Ship Name",
    write_reason: "Write reason ...",
    write_remarks: "Write remarks ...",
    select_accident_type: "Select Accident Type...",

    // ===== EVALUATION FORM =====
    new_evaluation: "New Evaluation",
    edit_evaluation: "Edit Evaluation",
    height: "Height",
    shipping: "Shipping",
    performance_evaluation: "Performance Evaluation",
    attachment: "Attachment",
    no_file_chosen: "No file chosen",
    enter_performance_evaluation: "Enter performance evaluation...",
    enter_evaluator: "Enter evaluator name",
    enter_period: "e.g., 2024-01 - 2024-12",
    enter_recommendation: "Enter recommendation",
    enter_comments: "Enter additional comments",
    enter_height: "Enter height in cm",
    enter_shipping: "Enter shipping details",
    select_rating: "Select Rating...",

    // ===== INJURY FORM =====
    add_injury: "Add Injury",
    edit_injury: "Edit Injury",
    illness: "Illness",
    medical_name: "Medical Name",
    hospital: "Hospital",
    treatment_start_date: "Treatment Start Date",
    recovery_date: "Recovery Date",
    public_private: "Public/Private",
    expense_won: "Expense_won",
    expense_ex: "Expense_ex",
    select_type: "Select Type...",

    // ===== HEALTH FORM =====
    add_health: "Add Health Record",
    edit_health: "Edit Health Record",
    size: "Size (H/W)",
    sight: "Sight (L/R)",
    hearing: "Hearing (L/R)",
    blood: "Blood",
    decision: "Decision",
    select_blood: "Select Blood Type...",
    select_decision: "Select Decision...",
  },

  kr: {
    // ===== COMMON =====
    app_name: "승무원 관리 시스템",
    sign_in: "로그인",
    sign_out: "로그아웃",
    cancel: "취소",
    save: "저장",
    delete: "삭제",
    edit: "수정",
    view: "보기",
    export: "내보내기",
    import: "가져오기",
    add: "추가",
    add_crew: "승무원 추가",
    add_new: "새로 추가",
    search: "검색",
    search_placeholder: "이름, 코드, 선박명으로 검색...",
    no_data: "데이터가 없습니다",
    loading: "로딩 중...",
    yes: "예",
    no: "아니오",
    ok: "확인",
    close: "닫기",
    back: "뒤로",
    next: "다음",
    previous: "이전",
    showing: "표시",
    of: "/",
    entries: "항목",
    record_registered: "기록이 성공적으로 등록되었습니다.",
    register_new: "새 등록",
    enter_details: "새로운",
    record: "기록을 추가하려면 아래 세부 정보를 입력하세요",
    reset: "초기화",
    save_record: "기록 저장",
    overview: "개요",
    total: "합계",
    new_person: "새 직원",

    // ===== NAVIGATION =====
    dashboard: "대시보드",
    crew: "승무원",
    "crew management": "승무원 관리",
    register: "등록",
    payment: "결제",
    settings: "설정",
    calendar: "달력",

    // ===== LOGIN =====
    user_name: "사용자 이름",
    password: "비밀번호",
    remember_me: "로그인 상태 유지",
    forgot_password: "비밀번호를 잊으셨나요?",
    login_success: "로그인 성공!",
    login_failed: "로그인 실패. 자격 증명을 확인하세요.",

    // ===== CREW =====
    crew_management: "승무원 관리",
    total_crews: "전체 승무원",
    on_board: "승선 중",
    active_crews: "활성 승무원",
    compliance_issues: "규정 준수 문제",
    boarding_vessel: "승선 선박",
    rank: "직급",
    seaman_code: "선원 코드",
    name: "이름",
    validity: "유효성",
    division: "구분",
    type: "유형",
    remaining: "잔여 일수",
    note: "비고",
    actions: "작업",
    view_details: "상세 보기",

    // ===== CERTIFICATE / SUMMARY =====
    certificate: "자격증",
    contract: "계약",
    ppt: "PPT",
    expire: "만료",
    days: "일",
    see_all: "전체 보기 →",
    vessel_name: "선박 이름",
    crew_class: "승무원 등급",
    sign_on: "승선",
    sign_off: "하선",
    include_period_contract: "계약 기간 포함",
    expired: "만료됨",
    active: "활성",
    inactive: "비활성",
    expired_contracts: "만료된 계약",
    expire_soon: "만료 예정",
    crew_name: "승무원 이름",
    overdue: "연체",
    education_name: "교육 명",
    expire_date: "만료 일자",
    remaining_date: "잔여 일수",

    // ===== DASHBOARD =====
    dashboard_overview: "대시보드 개요",
    total_crew: "전체 승무원",
    active_on_board: "승선 중",
    pending_contracts: "대기 중인 계약",
    expiring_certs: "만료 예정 자격증",
    quick_actions: "빠른 작업",
    recent_activity: "최근 활동",
    upcoming_tasks: "예정된 작업",

    // ===== FOOTER =====
    all_rights_reserved: "모든 권리 보유.",
    privacy_policy: "개인정보 처리방침",
    terms: "이용약관",
    support: "지원",
    version: "버전",

    // ===== MESSAGES =====
    logout_success: "로그아웃 성공!",
    logout_failed: "로그아웃 실패.",
    crew_created: "승무원이 성공적으로 생성되었습니다.",
    crew_updated: "승무원이 성공적으로 업데이트되었습니다.",
    crew_deleted: "승무원이 성공적으로 삭제되었습니다.",
    crew_not_found: "승무원을 찾을 수 없습니다.",
    confirm_delete: "삭제하시겠습니까?",
    confirm_delete_message:
      "이 기록을 정말 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",

    // ===== PROFILE =====
    profile: "프로필",
    personal_info: "개인 정보",
    contact_info: "연락처 정보",
    details_info: "상세 정보",
    address: "주소",
    phone: "전화번호",
    email: "이메일",
    birth_date: "생년월일",
    nationality: "국적",
    religion: "종교",

    // ===== APPOINTMENT =====
    appointment: "임명",
    replacement: "교체",
    family: "가족",
    health: "건강",
    injury: "부상",
    experiences: "경력",
    evaluation: "평가",
    certificates: "자격증",
    qualification: "자격",
    accident: "사고",

    // ===== PAYMENT =====
    payroll: "급여",
    payment_info: "결제 정보",
    bank_name: "은행명",
    account_number: "계좌번호",
    holder_name: "예금주",
    relation: "관계",
    basic_wage: "기본급",
    overtime: "초과 근무",
    allowances: "수당",
    deductions: "공제",
    currency: "통화",
    payment_date: "결제일",

    // ===== REGISTER FORM FIELDS =====
    license_name: "면허/자격증 명",
    grade_class: "등급/클래스",
    license_number: "면허 번호",
    issuing_authority: "발급 기관",
    issue_date: "발급일",
    expiry_date: "만료일",
    status: "상태",
    crew_member: "승무원",
    vessel: "선박",
    department: "부서",
    sign_on_date: "승선일",
    expected_sign_off: "예정 하선일",
    port_of_engagement: "승선 항구",
    contract_type: "계약 유형",
    outgoing_crew: "하선 승무원",
    reliever_name: "교체 승무원 이름",
    reliever_rank: "교체 승무원 직급",
    relief_port: "교체 항구",
    planned_date: "계획일",
    pay_period: "급여 기간",
    incident_date: "사고일",
    location: "선박 내 위치",
    accident_type: "사고 유형",
    severity: "심각도",
    reported_by: "보고자",
    description: "설명",
    action_taken: "조치 사항",
    injury_date: "부상일",
    body_part: "부상 부위",
    injury_type: "부상 유형",
    treatment: "치료 내용",
    days_off: "휴업 일수",
    fit_date: "업무 복귀일",
    notes: "비고",
    next_of_kin: "비상 연락처 이름",
    relationship: "관계",
    contact_number: "연락처",
    emergency_contact: "비상 연락처로 설정",
    blood_type: "혈액형",
    last_exam: "최근 건강검진일",
    fit_expiry: "업무 적합 만료일",
    vaccinations: "예방접종",
    allergies: "알레르기",
    medical_notes: "의료 비고",
    vessel_type: "선박 유형",
    grt: "총톤수 (GRT)",
    company: "회사",
    from_date: "시작일",
    to_date: "종료일",
    evaluation_period: "평가 기간",
    evaluator: "평가자",
    overall_rating: "종합 평점 (1-5)",
    technical_rating: "기술 능력 평점 (1-5)",
    teamwork_rating: "팀워크 평점 (1-5)",
    recommendation: "추천 사항",
    comments: "의견",
    certificate_name: "자격증 명",
    certificate_number: "자격증 번호",

    // ===== PERSONAL INFO FORM (KR) =====
    crew_code: "승무원 코드",
    position: "직위",
    hire_date: "고용일",
    name_korean: "이름 (한국어)",
    name_english: "이름 (영어)",
    name_chinese: "이름 (중국어)",
    address_eng: "주소 (영어)",
    address_korean: "주소 (한국어)",
    mobile: "휴대폰 번호",
    emergency_1: "비상 연락처 1",
    emergency_2: "비상 연락처 2",
    resident_id: "주민등록번호",
    education_university: "교육 (대학교)",
    education_school: "교육 (학교)",
    waist: "허리둘레",
    safety_shoes: "안전화",
    garments: "의복",
    drinking: "음주 (용량)",
    smoking: "흡연",
    long_service: "장기 근속",
    monthly_position: "월간 직위",
    chemical: "화학물질",
    tanker: "탱커",
    watch_office: "당직",
    mariners_license: "항해사 면허",
    telecom_license: "통신 면허",
    physical_exam: "건강검진",
    seaman_handbook: "선원 수첩",
    contract_period: "고용 계약 기간",
    preview: "미리보기",
    choose_file: "파일 선택",
    passport: "여권",
    add_new_crew: "새 승무원 추가",

    // ===== PLACEHOLDERS =====
    select_option: "선택하세요",
    select_position: "직급을 선택하세요",
    select_nationality: "국적을 선택하세요",
    enter_license: "면허 번호를 입력하세요",
    enter_passport: "여권 번호를 입력하세요",
    enter_telecom: "통신 면허를 입력하세요",
    enter_physical: "건강검진 일자를 입력하세요",
    enter_handbook: "선원 수첩 번호를 입력하세요",
    enter_contract: "계약 기간을 입력하세요",

    // ===== TAB PILLS =====
    tab_personal_info: "개인 정보",
    tab_qualifications: "자격",
    tab_appointment: "임명",
    tab_replacement: "교체",
    tab_payment: "결제",
    tab_family: "가족",
    tab_injury: "부상",
    tab_health: "건강",
    tab_experiences: "경력",
    tab_evaluation: "평가",
    tab_certificates: "자격증",
    tab_accident: "사고",
    crew_profile_sections: "승무원 프로필 섹션",

    // ===== QUALIFICATION FORM =====
    new_qualification: "새 자격증",
    edit_qualification: "자격증 수정",
    expiration: "만료",
    training_date: "교육 일자",
    attach_file: "파일 첨부",
    remarks: "비고",
    select_certificate: "자격증을 선택하세요...",
    enter_certificate_name: "자격증 명을 입력하세요",
    enter_expiration: "만료일을 입력하세요",
    enter_license_number: "면허 번호를 입력하세요",
    enter_remarks: "비고를 입력하세요",
    upload_drag_drop: "파일을 업로드하거나 드래그 앤 드롭하세요",
    max_file_size: "최대 파일 크기는 20MB입니다",
    supported_file_types: "지원 파일 형식: .png, .jpeg, .pdf, .csv",

    // ===== APPOINTMENT FORM =====
    new_appointment: "새 임명",
    edit_appointment: "임명 수정",
    deployment_division: "배치 부서",
    deployment_content: "배치 내용",
    ship_name: "선박 이름",
    boarding_date: "승선 일자",
    leaving_date: "하선 일자",
    boarding_period: "승선 기간",
    place: "장소",
    select_division: "부서를 선택하세요...",
    select_division_first: "먼저 부서를 선택하세요",
    select_deployment_content: "배치 내용을 선택하세요...",
    select_ship: "선박을 선택하세요...",
    select_rank: "직급을 선택하세요...",
    enter_boarding_period: "승선 기간을 입력하세요",
    enter_place: "장소를 입력하세요",
    select_contract: "계약 유형을 선택하세요...",

    // ===== REPLACEMENT FORM =====
    new_replacement: "새 교체",
    edit_replacement: "교체 수정",
    date: "일자",
    select_place: "장소를 선택하세요...",

    // ===== PAYMENT FORM =====
    new_payment: "새 결제 정보",
    edit_payment: "결제 정보 수정",
    account_holder: "예금주",
    select_bank: "은행을 선택하세요...",
    enter_account_holder: "예금주를 입력하세요",
    enter_account_number: "계좌번호를 입력하세요",
    select_relation: "관계를 선택하세요...",
    select_currency: "통화를 선택하세요...",

    // ===== FAMILY FORM =====
    family_details: "가족 정보",
    add_family_member: "가족 추가",
    edit_family_member: "가족 수정",
    no_family_members: "등록된 가족이 없습니다",
    fill_required_fields: "필수 항목을 입력해주세요",
    enter_name: "이름을 입력하세요",
    update: "수정",

    // ===== EXPERIENCE FORM =====
    new_experience: "새 경력",
    edit_experience: "경력 수정",
    company_name: "회사명",
    area: "항해 지역",
    ship_type: "선박 유형",
    board_leave: "승/하선",
    kw: "출력 (KW)",
    at_least_one_experience: "최소 1개 이상의 경력이 필요합니다",
    enter_company_name: "회사명을 입력하세요",
    enter_ship_name: "선박명을 입력하세요",
    select_area: "항해 지역을 선택하세요...",
    select_ship_type: "선박 유형을 선택하세요...",
    enter_board_leave: "승/하선을 입력하세요",
    enter_grt: "총톤수를 입력하세요",
    enter_kw: "출력을 입력하세요",
    select_board_leave: "승/하선을 선택하세요...",

    // ===== ACCIDENT FORM =====
    add_accident: "사고 추가",
    edit_accident: "사고 수정",
    accident_reason: "사고 사유",
    re_use: "재사용",
    accident_date: "사고 일자",
    accident_cost: "사고 비용",
    etc: "기타",
    choose_ship_name: "선박을 선택하세요",
    write_reason: "사유를 입력하세요 ...",
    write_remarks: "비고를 입력하세요 ...",
    select_accident_type: "사고 유형을 선택하세요...",

    // ===== EVALUATION FORM =====
    new_evaluation: "새 평가",
    edit_evaluation: "평가 수정",
    height: "키",
    shipping: "선적",
    performance_evaluation: "성과 평가",
    attachment: "첨부 파일",
    no_file_chosen: "선택된 파일 없음",
    enter_performance_evaluation: "성과 평가를 입력하세요...",
    enter_evaluator: "평가자 이름을 입력하세요",
    enter_period: "예: 2024-01 - 2024-12",
    enter_recommendation: "추천 사항을 입력하세요",
    enter_comments: "추가 의견을 입력하세요",
    enter_height: "키(cm)를 입력하세요",
    enter_shipping: "선적 정보를 입력하세요",
    select_rating: "평점을 선택하세요...",

    // ===== INJURY FORM =====
    add_injury: "부상 추가",
    edit_injury: "부상 수정",
    illness: "질병",
    medical_name: "의료 명",
    hospital: "병원",
    treatment_start_date: "치료 시작 일자",
    recovery_date: "회복 일자",
    public_private: "공공/민간",
    expense_won: "비용_won",
    expense_ex: "비용_ex",
    select_type: "유형을 선택하세요...",

    // ===== HEALTH FORM =====
    add_health: "건강 기록 추가",
    edit_health: "건강 기록 수정",
    size: "크기 (키/몸무게)",
    sight: "시력 (좌/우)",
    hearing: "청력 (좌/우)",
    blood: "혈액형",
    decision: "판정",
    select_blood: "혈액형을 선택하세요...",
    select_decision: "판정을 선택하세요...",
  },
};


const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem("language");
    return savedLanguage || "en";
  });

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (lang) => {
    if (lang === "en" || lang === "kr") {
      setLanguage(lang);
      localStorage.setItem("language", lang);

      // ✅ Update API Header (Standard way)
      if (api && api.defaults) {
        api.defaults.headers["Accept-Language"] = lang;
      }

      document.documentElement.lang = lang;
      console.log(`🌐 Language changed to: ${lang.toUpperCase()}`);
    }
  };

  useEffect(() => {
    // ✅ Set default language header on app load
    if (api && api.defaults) {
      api.defaults.headers["Accept-Language"] = language;
    }
    document.documentElement.lang = language;
  }, [language]);

  const value = {
    language,
    setLanguage: changeLanguage,
    t,
    isKorean: language === "kr",
    isEnglish: language === "en",
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;